version: "3.8"
services:
  backend:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT}

  frontend:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=${FRONTEND_PORT}


