version: "3.8"
services:
  backend:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev
    volumes:
      - ./apps/backend:/app/backend:delegated
      - /app/backend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=${BACKEND_PORT}

  frontend:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-dev
    volumes:
      - ./apps/frontend:/app/frontend:delegated
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=${FRONTEND_PORT}


